import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="w-full h-full flex px-5  sm:px-0 flex-col items-center justify-center"
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
